### ISSUE TITLE
Error logging out. Error destroying token

### ISSUE THREAD

**Issue by guti7** [dropbox/dbximages#2]
I'm having an issue troubleshooting the logout flow for my version.
I get an error when it attempts to revoke the token. I also get the error using the demo heroku app provided. I'm unsure how to proceed.

**Comment by rubenrincon** [comment]
Hello Jose,
can you provide more information on the errors you are getting?
Is the problem that after you do the /logout you end up in the authorization screen?  if that is the case, it is the expected behavior as you are logging out of the middleware, your browser is still logged into Dropbox.  To logout of Dropbox you can also do dropbox.com/logout
